name=iBUS_ESP32
version=1.0.0
author=Sachintha R Balasooriya
maintainer=Sachintha R Balasooriya
sentence=Lightweight iBus receiver library for ESP32.
paragraph=Parses FlySky iBus protocol directly over HardwareSerial with checksum validation. No external components required. Supports up to 12 channels.
category=Communication
url=https://github.com/titanX108/iBUS_ESP32
architectures=esp32
includes=iBUS_ESP32.h
